name: Generate Snake Animation

on:
  schedule:
    # Executa diariamente às 00:00 (horário configurado em TIMEZONE_CRON)
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./output/github-contribution-grid-snake.gif
          svg_out_path: ./output/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          branch: main
          message: 'Generate contribution snake'
          add: './output/github-contribution-grid-snake.*'
