name: Generate Snake
on:
  schedule: [{ cron: "0 3 * * *" }]  # diário 03:00 {{TIMEZONE_CRON}} approx
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: "{{ORG_USERNAME_FOR_WIDGETS}}"
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
